general:
  startup_commands: []
  shutdown_commands: []
  config_reload_commands: []

  focus_follows_cursor: false

  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: false

    trigger: 'monitor_focus'

  hide_method: 'cloak'

  show_all_in_taskbar: true

gaps:
  scale_with_dpi: true

  inner_gap: '20px'

  outer_gap:
    top: '20px'
    right: '20px'
    bottom: '20px'
    left: '20px'

window_effects:
  focused_window:
    border:
      enabled: false
      color: '#8dbcff'

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: false
      style: 'square'

    transparency:
      enabled: false
      opacity: '95%'

  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  initial_state: 'tiling'

  state_defaults:
    floating:
      centered: true

      shown_on_top: false

window_rules:
  - commands: ['ignore']
    match:
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1' }

    fullscreen:
      maximized: false

      shown_on_top: false

workspaces:
  - name: '1'
